force-app/main/default/objects/Dataverse_Contact_Request__c/Dataverse_Contact_Request__c.object-meta.xml
<CustomObject>
    <description>Represents a request from the AGSC Microsoft Dataverse environment to insert or update a contact</description>
    <label>Dataverse Contact Request</label>
    <nameField>
        <displayFormat>DCR-{00000}</displayFormat>
        <label>Dataverse Contact Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dataverse Contact Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dataverse_Contact_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dataverse Contact Requests</relationshipLabel>
    <relationshipName>Dataverse_Contact_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dataverse_Contact_Request__c/fields/Parent_Guardian_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Guardian_First_Name__c</fullName>
    <label>Parent/Guardian First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataverse_Contact_Request__c/fields/Parent_Guardian_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Guardian_Last_Name__c</fullName>
    <label>Parent/Guardian Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataverse_Contact_Request__c/fields/Player_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Player_First_Name__c</fullName>
    <label>Player First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataverse_Contact_Request__c/fields/Player_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Player_Last_Name__c</fullName>
    <label>Player Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataverseContactService_Test.cls
@IsTest
private class DataverseContactService_Test {

    @TestSetup
    static void makeData() {
        List<Contact> lstContacts = TestDataFactory.createContacts(1);
        insert lstContacts;
    }
    
    @IsTest
    static void testMatchingContact() {
        Contact ct = [SELECT Id, FirstName, LastName FROM Contact LIMIT 1];

        Dataverse_Contact_Request__c dcr = new Dataverse_Contact_Request__c();
        dcr.Contact__c = ct.Id;
        dcr.Player_First_Name__c = ct.FirstName;
        dcr.Player_Last_Name__c = ct.LastName;
        
        Test.startTest();
        DataverseContactService service = new DataverseContactService(dcr);
        Id contactId = service.getContactId();
        Test.stopTest();

        Assert.areEqual(ct.Id, contactId, 'Should have received the matching contact id');
    }

    @IsTest
    static void testNewContact() {
        Contact ct = [SELECT Id, FirstName, LastName FROM Contact LIMIT 1];

        Dataverse_Contact_Request__c dcr = new Dataverse_Contact_Request__c();
        dcr.Contact__c = null;
        dcr.Player_First_Name__c = 'Newguy';
        dcr.Player_Last_Name__c = 'Test';
        dcr.Parent_Guardian_First_Name__c = 'Parentnewguy';
        dcr.Parent_Guardian_Last_Name__c = 'Test';

        Test.startTest();
        DataverseContactService service = new DataverseContactService(dcr);
        Id contactId = service.getContactId();
        Test.stopTest();

        Assert.areNotEqual(ct.Id, contactId, 'Should have received a new contact');
    }

}